<?php

namespace Kairos\Bundle\GeoTimezoneBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * GeoNameCityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeoNameCityRepository extends EntityRepository
{
    /**
     * Get the geo name city object closest from the longitude and latitude given
     *
     * @param $lng
     * @param $lat
     * @return bool
     */
    public function getClosestGeoTimezone($lat, $lng)
    {
        $sqlQuery = $this->buildGeoNameCityClosestQuery();
        $query = $this->_em->createQuery($sqlQuery);

        $query->setParameter('lng', $lng);
        $query->setParameter('lat', $lat);
        $query->setMaxResults(1);
        $query->setHint(Query::HINT_CUSTOM_OUTPUT_WALKER, 'CrEOF\Spatial\ORM\Query\GeometryWalker');

        try {
            $result = $query->getResult();
            if (count($result) > 0 && $result[0][0] instanceof \Kairos\Bundle\GeoTimezoneBundle\Entity\GeoNameCity) {
                $geoNameCity = $result[0][0];
                return $geoNameCity->getTimezone();
            }
        } catch (\Exception $e) {
            exit($e->getMessage());
        }

        return false;
    }

    /**
     * @return bool|string
     */
    private function buildGeoNameCityClosestQuery()
    {
        if($this->_em->getConnection()->getDatabasePlatform()->getName() == 'postgresql') {
            return 'SELECT gnc, ST_Distance(
                        ST_Point(:lng,:lat),
                        gnc.coordinates,
                        false
                      ) as distance
                      FROM Kairos\Bundle\GeoTimezoneBundle\Entity\GeoNameCity gnc
                      ORDER BY distance ASC
                      ';
        }
        elseif($this->_em->getConnection()->getDatabasePlatform()->getName() == 'mysql') {
            return 'SELECT gnc, (SQRT(POW(gnc.longitude - :lng , 2) + POW(gnc.latitude - :lat, 2)) * 100) as distance
                      FROM Kairos\Bundle\GeoTimezoneBundle\Entity\GeoNameCity gnc
                      ORDER BY distance ASC
                      ';
        }

        return false;
    }
}
